name: Build and Deploy
on:
  workflow_run:
    branches: [main]
    workflows: ['CI']
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-web:
    name: Build and DeployDeploy Web App to Netlify

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: Build the web app
        run: bun run build:web

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: 'Deploy from GitHub Actions'
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: 'echo skipping dependencies installation'
          build_directory: dist
          build_command: 'echo skipping redundant build command'
