name: Expo Doctor
on: [push]
jobs:
  ci:
    name: Doctor Checkup

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['21.5.0']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'America/New_York'

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: 📦 Install dependencies
        run: npm install --legacy-peer-deps

      - name: Expo Doctor
        run: npx expo-doctor
