name: CI
on: [push]
jobs:
  ci:
    name: Compile Typescript

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: TypeCheck
        run: bun ts:check

      - name: Lint
        run: bun lint

      - name: Format
        run: bun format

      - name: Test
        run: CI=true bun test

      - name: Build
        run: bun run build:web
